resolver: lts-8.9


packages:
- '.'

extra-deps:
  - th-printf-0.3.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
